[tools]
node = "latest"
bun = "latest"
"npm:opencode-ai" = "latest"
python = "latest"
uv = "latest"

[settings.npm]
package_manager = "bun"

[env]
_.python.venv = { path = ".venv", create = true }
OPENCODE_ENABLE_EXA = "true"
EDITOR = "code --wait"

[tasks.sync]
description = "Sync Python dependencies"
run = "uv sync"